name: Buy 645 Lotto Every friday

on:
  workflow_dispatch:

jobs:
  buy-lotto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run lotto bot
        env: 
          LOTTO_ID: ${{ secrets.LOTTO_ID }}
          LOTTO_PW: ${{ secrets.LOTTO_PW }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python buy_645_lotto.py
